### ISSUE TITLE
asti

### ISSUE THREAD

**Issue by Aestek** [asticode/go-astiencoder#1]
astiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiastiasti

**Comment by asticode** [comment]
❤️
