### ISSUE TITLE
goav - howto

### ISSUE THREAD

**Issue by ivanjaros** [asticode/go-astiencoder#4]
Since goav has disabled issues i will ask in here:
I have few income streams(srt->ts->h264/aac, rtmp->flv->h264/aac,...) that i need to "normalize" into av1 and then create different quality versions(ie 240p, 360p, 4801p, 720p and 1080p). I am looking at goav but I am not seeing functions that look like they will do what I am after.

Can you hint at where to begin? I will most likely have the input codec info so I do not need to guess the codec or the container to begin with. I just need to take the packets and transcode them from codec A to codec B and that is about it.

**Comment by asticode** [comment]
Not enabling issues on `goav` was my bad. I just fixed it. Could you close this issue and open a new one in `goav` repo for better tracability ?
