### ISSUE TITLE
Need help when installing package

### ISSUE THREAD

**Issue by aalvarez89** [asticode/go-astiencoder#5]
Hello! I'm having some troubles when installing the packages, I get several error messages but I can't really tell if they're errors or just warnings. Running "make version" won't work tho, it also gives me an error
After installing packages:
![image](https://user-images.githubusercontent.com/24280230/95125434-f70c6800-0722-11eb-9a41-5c06152d6b08.png)

After running "make version"
![image](https://user-images.githubusercontent.com/24280230/95125553-23c07f80-0723-11eb-8384-141c324747da.png)

I'm also using my own version of ffmpeg which I installed with the dependencies I needed to test my environment. Can I remove the ffmpeg install that comes in astiencoder/Makefile?
Thank you very much

**Comment by asticode** [comment]
Can you run `ls -l` in `go-astiencoder` folder and paste the ouput here ?

**Comment by asticode** [comment]
Can you run `ls -l` in `go-astiencoder` folder and paste the ouput here ?

**Comment by aalvarez89** [comment]
> Can you run `ls -l` in `go-astiencoder` folder and paste the ouput here ?

I get this 
`total 272
-rw-rw-r-- 1 andrew andrew   1071 Oct  5 20:33 LICENSE
-rw-rw-r-- 1 andrew andrew    773 Oct  5 20:33 Makefile
-rw-rw-r-- 1 andrew andrew   6605 Oct  5 20:33 README.md
drwxrwxr-x 3 andrew andrew   4096 Oct  5 20:33 astiencoder
drwxrwxr-x 3 andrew andrew   4096 Oct  5 20:33 cmd
drwxrwxr-x 2 andrew andrew   4096 Oct  5 20:33 doc
-rw-rw-r-- 1 andrew andrew   7523 Oct  5 20:33 event.go
-rw-rw-r-- 1 andrew andrew    892 Oct  5 20:33 event_test.go
drwxrwxr-x 3 andrew andrew   4096 Oct  5 20:33 examples
-rw-rw-r-- 1 andrew andrew    326 Oct  5 20:33 go.mod
-rw-rw-r-- 1 andrew andrew   2119 Oct  5 20:33 go.sum
drwxrwxr-x 2 andrew andrew   4096 Oct  5 20:33 libav
-rw-rw-r-- 1 andrew andrew  10206 Oct  5 20:33 node.go
-rw-rw-r-- 1 andrew andrew   6138 Oct  5 20:33 server.go
-rw-rw-r-- 1 andrew andrew 185377 Oct  5 20:33 server_bind.go
drwxrwxr-x 2 andrew andrew   4096 Oct  5 20:33 web
-rw-rw-r-- 1 andrew andrew   3885 Oct  5 20:33 workflow.go
-rw-rw-r-- 1 andrew andrew   2617 Oct  5 20:33 workflow_recording.go`

**Comment by aalvarez89** [comment]
I followed the repo install instructions from scratch, I installed ffmpeg with make install-ffmpeg configure "_...extra-libs_" 
![image](https://user-images.githubusercontent.com/24280230/95219841-d6e0b580-07c3-11eb-8d52-0dbbe76b04c1.png)

Then I ran make build and I got this
![image](https://user-images.githubusercontent.com/24280230/95219677-abf66180-07c3-11eb-94d4-68e136db3f91.png)

**Comment by asticode** [comment]
Which version of go are you using ? `go version`

**Comment by aalvarez89** [comment]
golang 1.10

**Comment by aalvarez89** [comment]
Thank you very much, it finally worked. I upgraded to 1.15 and running make version and make build work as intended.

I tried to execute one of the examples but I cant seem to get it working 
![image](https://user-images.githubusercontent.com/24280230/95226829-676ec400-07cb-11eb-836a-844db3e1181c.png)

**Comment by asticode** [comment]
What if you run `make example example=copy` instead ?

**Comment by aalvarez89** [comment]
I get this: 
![image](https://user-images.githubusercontent.com/24280230/95229204-48256600-07ce-11eb-9dac-085565a89bef.png)

**Comment by asticode** [comment]
This is what is expected 👍 

My guess is that when you run the `go run` yourself without providing the `CGO` flags, it links to another `ffmpeg` installation

**Comment by aalvarez89** [comment]
I see, how do I specify the correct paths? I'm already using the provided ffmpeg version but I havent set any environment variables for it or for any of the `CGO_CFLAGS`, `CGO_LDFLAGS` and `PKG_CONFIG_PATH` environment variables

**Comment by asticode** [comment]
When you run `make example example=copy`, the executed command is printed at the top. All necessary environment variables are visible there.

**Comment by aalvarez89** [comment]
Thanks a lot for the help, everything has worked well so far.
I have a couple of extra questions, where would I have to add the options to have it read one video and run multiple encoding processes in one video? 
for example, something like what this ffmpeg command does:
```
ffmpeg -i input.mp4 \
 -c:a aac -vf scale=640x360 -c:v libx264 out1.mp4 \
 -c:a aac -vf scale=1280x720 -c:v libx264 out2.mp4
```

**Comment by asticode** [comment]
You're trying to use the `out-of-the-box encoder` located in the `astiencoder` folder or you're trying to use the framework in your code ?

**Comment by aalvarez89** [comment]
the out-of-the-box encoder.
I guess that what I wanted to know is how to incorporate that on the json file options

**Comment by asticode** [comment]
You should be able to do it like that:

```json
{
  "inputs": {
    "default": {
      "url": "/path/to/input.mp4"
    }
  },
  "outputs": {
    "out1": {
      "url": "/path/to/out1.mp4"
    },
    "out2": {
      "url": "/path/to/out2.mp4"
    }
  },
  "operations": {
    "audio1": {
      "codec": "aac",
      "inputs": [
        {
          "media_type": "audio",
          "name": "default"
        }
      ],
      "outputs": [
        {
          "name": "out1"
        }
      ]
    },
    "audio2": {
      "codec": "aac",
      "inputs": [
        {
          "media_type": "audio",
          "name": "default"
        }
      ],
      "outputs": [
        {
          "name": "out2"
        }
      ]
    },
    "video1": {
      "codec": "libx264",
      "height": 360,
      "inputs": [
        {
          "media_type": "video",
          "name": "default"
        }
      ],
      "outputs": [
        {
          "name": "out1"
        }
      ],
      "width": 640
    },
    "video2": {
      "codec": "libx264",
      "height": 720,
      "inputs": [
        {
          "media_type": "video",
          "name": "default"
        }
      ],
      "outputs": [
        {
          "name": "out2"
        }
      ],
      "width": 1280
    }
  }
}
```

**Comment by aalvarez89** [comment]
Hello! Thanks again for all of your help. Everything has been going really great. I'd like to ask you: how can specify the output format as "flv" if I want to have an RTMP url as an output?

**Comment by asticode** [comment]
@aalvarez89 I've added a `format` key to the outputs like that :

```json
{
  "outputs": {
    "out1": {
      "format": "flv",
      "url": "rtmp://path/to/rtmp"
    }
  },
}
```

You should pull the latest changes

**Comment by aalvarez89** [comment]
Hello! Thanks for your help before. I was doing some tests and I couldn't get the options -tune and -preset working, I believe they're not being parsed from the JSON file, is there any way to add them?

**Comment by asticode** [comment]
Have you tried using the `dict` key in `operations` items?

```json
    "video1": {
      "codec": "libx264",
      "dict": "tune=film,preset=fast",
      "height": 360,
      "inputs": [
        {
          "media_type": "video",
          "name": "default"
        }
      ],
      "outputs": [
        {
          "name": "out1"
        }
      ],
      "width": 640
    }
```

**Comment by aalvarez89** [comment]
Ah that worked! So that means that `dict` sets the settings for the codec? 
Also, I was reading through the code and I found that you implemented stuff for hardware acceleration, how would I add the options if I wanna decode with an nvidia GPU?

**Comment by asticode** [comment]
> So that means that dict sets the settings for the codec?

Yes it does.

> Also, I was reading through the code and I found that you implemented stuff for hardware acceleration, how would I add the options if I wanna decode with an nvidia GPU?

Can you link to the portion of code you're mentionning?

**Comment by aalvarez89** [comment]
Hello, I may have figured out the GPU stuff, thanks anyways. I restarted another project from scratch but I noticed you added a 'stater', I can't run the encoder anymore but idk what or where to pass the required information for that. What does it do?

**Comment by aalvarez89** [comment]
it's on goav/avcodec/avcodec.go line 39 and 325.
I'm using a gpu to decode and decode but I can't figure out how to set cuvid as my -hwaccel and other options like hwaccel_output_format and the codec on the input settings

**Comment by aalvarez89** [comment]
Sorry, I searched throughout all the code but I couldn't find any references that allowed me to instantiate the settings for the hardware acceleration mode. How can I approach that?
I appreciate your advise,
thanks

**Comment by asticode** [comment]
@aalvarez89 for now there's no way to use the GPU since what you saw in `goav` is deprecated.
