### ISSUE TITLE
Remuxing of 2 streams

### ISSUE THREAD

**Issue by FireMasterK** [asticode/go-astiencoder#6]
Hi,

My goal is to create a muxing server that would mux an audio and video stream from 2 different URLs, in memory without re-encoding the entire video. Would this be possible using this library?

With `ffmpeg`, I can manually mux them like so:
```
ffmpeg -i https://server/video.webm -i https://server/audio.webm -c copy output.webm
```

But this approach would create a file called output.webm, would it be possible to do this without creating a file?

I'd also like to be able to have the server to support `Range` requests which basically request content with the help of bytes, which means I also need to be able to seek somehow with bytes.

I've been looking for a solution for a few weeks now, so any help is appreciated!

Thanks in advance!

**Comment by asticode** [comment]
The simplest solution is setting up 2 demuxers (one for the audio and one for the video) and 1 muxer (for your memory output), and connect the 2 demuxers to the muxer. This would do the same as `ffmpeg` and would create a file.

I'm not sure you can store .webm chunks in memory, don't they require a start and end global header ?

**Comment by FireMasterK** [comment]
> The simplest solution is setting up 2 demuxers (one for the audio and one for the video) and 1 muxer (for your memory output), and connect the 2 demuxers to the muxer. This would do the same as `ffmpeg` and would create a file.

That seems like a clean way to do it, I'll give this a shot, but you did say it creates a file, wouldn't it be possible without one? In ffmpeg, pipes can be used to do so for this.

> I'm not sure you can store .webm chunks in memory, don't they require a start and end global header ?

I thought `ffmpeg` fetches the required headers and seeks to wherever necessary after that. Range requests allow you to seek to whichever part of the file when necessary.

Another question, ffmpeg allows you to seek in a video using a time, would it be possible to seek with bytes instead in the muxer?

**Comment by asticode** [comment]
> That seems like a clean way to do it, I'll give this a shot, but you did say it creates a file, wouldn't it be possible without one? In ffmpeg, pipes can be used to do so for this.

Right now this lib only handles writing to a file. Writing to memory would be possible but a change would be needed.

> Another question, ffmpeg allows you to seek in a video using a time, would it be possible to seek with bytes instead in the muxer?

If data is written to a []byte, I guess seeking with bytes is doable.
